#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

if [ -d /filesystem/home/pi ]
then
    unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
fi
if [ -d /filesystem/home/root ]
then
    unpack /filesystem/home/root /root root
fi
if [ -d /filesystem/boot ]
then
    unpack /filesystem/boot /boot
fi

echo "This is an example module, install and set up what you need here!"
echo "$HOMEAUTOMATION_VAR"
echo "$HOMEAUTOMATION_PKGS"

apt_update_skip
check_install_pkgs ${HOMEAUTOMATION_PKGS}

pushd  /home/pi/workspace
  gitclone HOMEAUTOMATION_HOMEAUTOMATION_REPO
  gitclone HOMEAUTOMATION_GETTINGSTARTETESP_REPO
popd

# Unpack root at the end, so files are modified before
if [ -d /filesystem/root ]
then
  unpack /filesystem/root /
fi
