#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set -x
set -e

source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

echo "This is an example module, install and set up what you need here!"
echo "$PYTHONGPIO_VAR"
echo "$DEVOPSPIOS_PKGS"

apt_update_skip
check_install_pkgs ${PYTHONGPIO_PKGS}

sed -i -E 's;^#(dtparam=i2c_arm=on);\1;g' /boot/config.txt
sed -i "s/dtparam=i2c_arm=on/dtparam=i2c_arm=on\ndtparam=i2c_vc=on/g" /boot/config.txt

for i in "do_i2c" "do_spi" "do_serial"
do
  set_config_var $i 0
done

pushd  /home/pi/workspace
  gitclone PYTHONGPIO_GPIOBLOCKLY_REPO
popd

su - -c "cd /home/${BASE_USER}/bin && virtualenv -p python3 jupyter-venv" "${BASE_USER}"
su - -c "source /home/${BASE_USER}/bin/jupyter-venv/bin/activate && pip install -U jupyterlab" "${BASE_USER}"

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

systemctl enable jupyter.service
