#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set +x
set -e

source /common.sh
install_cleanup_trap

if [ -d /filesystem/home/pi ]
then
    unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
fi
if [ -d /filesystem/home/root ]
then
    unpack /filesystem/home/root /root root
fi
if [ -d /filesystem/boot ]
then
    unpack /filesystem/boot /boot
fi

echo "This is an example module, install and set up what you need here!"
echo "$DEVOPS_VAR"
echo "$DEVOPS_PKGS"

apt_update_skip
check_install_pkgs ${DEVOPS_PKGS}

if [ -f /usr/local/bin/docker-compose -a ! -f /usr/bin/docker-compose ]
then
   ln -s /usr/local/bin/docker-compose /usr/bin/ 2>/dev/null || true
fi 

# Unpack root at the end, so files are modified before
if [ -d /filesystem/root ]
then
    unpack /filesystem/root /
fi

echo "Installing prometheus"

wget https://github.com/prometheus/prometheus/releases/download/v${DEVOPS_PROMETHEUS_VERSION}/prometheus-${DEVOPS_PROMETHEUS_VERSION}.linux-arm64.tar.gz
tar xfz prometheus-${DEVOPS_PROMETHEUS_VERSION}.linux-arm64.tar.gz
rm prometheus-${DEVOPS_PROMETHEUS_VERSION}.linux-arm64.tar.gz 
mv prometheus-${DEVOPS_PROMETHEUS_VERSION}.linux-arm64/ /usr/local/bin/prometheus

echo "Installing Grafana"

wget https://dl.grafana.com/enterprise/release/grafana-enterprise_${DEVOPS_GRAFANA_VERSION}_arm64.deb
dpkg -i grafana-enterprise_${DEVOPS_GRAFANA_VERSION}_arm64.deb
rm grafana-enterprise_${DEVOPS_GRAFANA_VERSION}_arm64.deb
