#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set +x
set -e

source /common.sh
install_cleanup_trap

if [ -d /filesystem/home/pi ]
then
    unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
fi
if [ -d /filesystem/home/root ]
then
    unpack /filesystem/home/root /root root
fi
if [ -d /filesystem/boot ]
then
    unpack /filesystem/boot /boot
fi

echo "From here the DEVOPS-Module starts"
echo "$DEVOPS_VAR auf ${BASE_DISTRO}/${BASE_ARCH}"
echo "$DEVOPS_PKGS"

echo "Add Docker's official GPG key"
apt-get update
apt-get install ca-certificates curl
install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/${BASE_DISTRO}/gpg -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

echo "Add the repository to Apt sources"
ARCH=debian
if [ $(. /etc/os-release && echo "$ID") == "ubuntu" ]
then
    ARCH=ubuntu
fi
echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/${ARCH} $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
apt-get update


apt_update_skip
check_install_pkgs ${DEVOPS_PKGS}

usermod -aG docker ${BASE_USER}

if [ -f /usr/local/bin/docker-compose -a ! -f /usr/bin/docker-compose ]
then
   ln -s /usr/local/bin/docker-compose /usr/bin/ 2>/dev/null || true
fi 

# Unpack root at the end, so files are modified before
if [ -d /filesystem/root ]
then
    unpack /filesystem/root /
fi

LC_ALL=C.UTF-8 ansible --inventory localhost, --connection local --module-name ping localhost

echo "Installing prometheus"

wget --quiet https://github.com/prometheus/prometheus/releases/download/v${DEVOPS_PROMETHEUS_VERSION}/${DEVOPS_PROMETHEUS}.tar.gz
tar xfz ${DEVOPS_PROMETHEUS}.tar.gz
rm ${DEVOPS_PROMETHEUS}.tar.gz
# The /opt/prometheus directory already exists by unpack.
mv ${DEVOPS_PROMETHEUS}/* /opt/prometheus/
chmod a+w /opt/prometheus/data
chown --recursive root:root /opt/prometheus
ln --symbolic /opt/prometheus/prometheus /usr/local/bin/prometheus

echo "Installing Grafana"

wget https://dl.grafana.com/enterprise/release/${DEVOPS_GRAFANA}.deb
dpkg --install ${DEVOPS_GRAFANA}.deb
rm ${DEVOPS_GRAFANA}.deb
