#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set +x
set -e

source /common.sh
install_cleanup_trap

if [ -d /filesystem/home/pi ]
then
    unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
fi
if [ -d /filesystem/home/root ]
then
    unpack /filesystem/home/root /root root
fi
if [ -d /filesystem/boot ]
then
    unpack /filesystem/boot /boot
fi

echo "From here the MYBASE-Module starts"
echo "$MYBASE_VAR"
echo "$MYBASE_PKGS"

apt_update_skip
check_install_pkgs ${MYBASE_PKGS}

if [ ${BASE_DISTRO} != "ubuntu" ]
then
    apt-get remove cryptsetup
fi

echo 'Install doitpi ansibele and test environment'
pushd  /home/${BASE_USER}/workspace
  gitclone MYBASE_DOITPI_ANSIBLE_REPO
  chown -R "${BASE_USER}": ./doitpi-ansible
  cd ./doitpi-ansible
  LC_ALL=C.UTF-8 ansible-playbook --extra-vars ansible_user_id=${BASE_USER} --extra-vars ansible_user_dir=/home/${BASE_USER} --tags ${MYBASE_DOITPI_ANSIBLE_REPO_TAGS} --limit lokal main.yaml
  cd -
  gitclone MYBASE_DOITPI_TEST_REPO
  chown -R "${BASE_USER}": ./doitpi-test
  su -c "cd ./doitpi-test; python3 -m venv .venv; source .venv/bin/activate && pip install -r requirements.txt" "${BASE_USER}"
popd

echo 'Die locale werden mit ansible installiert'

echo 'Configure dhclient'
if [ -f /etc/dhcp/dhclient.conf ]
then
    echo 'Do not try too long to reach the DHCPD server (blocks booting)'
    sed -i "s/#timeout 60;/timeout 10;/g" /etc/dhcp/dhclient.conf
    # By default, the client retries to contact the DHCP server after five min.
    # Reduce this time to 20 sec.
    sed -i "s/#retry 60;/retry 20;/g" /etc/dhcp/dhclient.conf
fi

echo 'Setup gpu memory'
# ToDo Ubuntu nicht machen?
if [ -f /boot/config.txt ]
then
    echo "gpu_mem=16M" >> /boot/config.txt
fi
# Unpack root at the end, so files are modified before
if [ -d /filesystem/root ]
then
    unpack /filesystem/root /
fi
# systemctl enable codeserver.service
systemctl enable firstboot.service
