#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set +x
set -e

source /common.sh
install_cleanup_trap

if [ -d /filesystem/home/pi ]
then
    unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
fi
if [ -d /filesystem/home/root ]
then
    unpack /filesystem/home/root /root root
fi
if [ -d /filesystem/boot ]
then
    unpack /filesystem/boot /boot
fi

echo "From here the MYBASE-Module starts"
echo "$MYBASE_VAR"
echo "$MYBASE_PKGS"

apt_update_skip
check_install_pkgs ${MYBASE_PKGS}

# ToDo Bootwait für ubuntu arm64
if [ ${BASE_DISTRO} != "ubuntu" ]
then
    apt-get remove cryptsetup
fi

echo 'Install doitpi test environment'
pushd  /home/${BASE_USER}/workspace
  gitclone MYBASE_DOITPI_TEST_REPO
  chown -R "${BASE_USER}": ./doitpi-test
  su -c "cd ./doitpi-test; python3 -m venv .venv; source .venv/bin/activate && pip install -r requirements.txt" "${BASE_USER}"
popd

echo 'Install locale'
sed -i -E 's;^#\s(de_DE.UTF-8.*);\1;g' /etc/locale.gen
sed -i -E 's;^#\s(en_US.UTF-8.*);\1;g' /etc/locale.gen
sed -i -E 's;^#\s(nl_NL.UTF-8.*);\1;g' /etc/locale.gen
sed -i -E 's;^#\s(fr_FR.UTF-8.*);\1;g' /etc/locale.gen
locale-gen
# Geht nicht in chroot
#localectl set-locale LANG=de_DE.UTF-8

echo 'Install Codeserver'
TEMP_DEB="$(mktemp)" && wget --quiet --output-document="$TEMP_DEB" \
                    ${MYBASE_CODESERVER_URL} && dpkg --install "$TEMP_DEB"
rm -f "$TEMP_DEB"

echo 'Configure dhclient'
if [ -f /etc/dhcp/dhclient.conf ]
then
    echo 'Do not try too long to reach the DHCPD server (blocks booting)'
    sed -i "s/#timeout 60;/timeout 10;/g" /etc/dhcp/dhclient.conf
    # By default, the client retries to contact the DHCP server after five min.
    # Reduce this time to 20 sec.
    sed -i "s/#retry 60;/retry 20;/g" /etc/dhcp/dhclient.conf
    echo "Disable wait for network"
    if grep bookworm /etc/os-release
    then
        echo "Bootwait not working in bookworm"
    else
        # ToDo Bootwait für ubuntu arm64
        if [ ${BASE_DISTRO} != "ubuntu" ]
        then
            set_config_var do_boot_wait 1
            raspi-config nonint do_boot_wait 1
        fi
    fi
fi

echo 'Setup gpu memory'
# ToDo Ubuntu nicht machen?
echo "gpu_mem=16M" >> /boot/config.txt
# Unpack root at the end, so files are modified before
if [ -d /filesystem/root ]
then
    unpack /filesystem/root /
fi
systemctl enable codeserver.service
systemctl enable firstboot.service
