#!/usr/bin/env bash
# <Script Name>
# <Description what this module does>
# Written by <Author>
# GPL V3
########


# Source error handling, leave this in place
set +x
set -e

source /common.sh
install_cleanup_trap

if [ -d /filesystem/home/pi ]
then
    unpack /filesystem/home/pi /home/"${BASE_USER}" "${BASE_USER}"
fi
if [ -d /filesystem/home/root ]
then
    unpack /filesystem/home/root /root root
fi
if [ -d /filesystem/boot ]
then
    unpack /filesystem/boot /boot
fi

echo "This is an example module, install and set up what you need here!"
echo "$PLATFORMIO_VAR"
echo "$PLATFORMIO_PKGS"

apt_update_skip
check_install_pkgs ${PLATFORMIO_PKGS}

su - -c "cd /home/${BASE_USER}/.platformio && python3 -m venv penv" "${BASE_USER}"
su - -c "source /home/${BASE_USER}/.platformio/penv/bin/activate && pip install -U platformio" "${BASE_USER}"

if [ ! -f /etc/udev/rules.d/99-platformio-udev.rules ]
then
  wget -P /etc/udev/rules.d https://raw.githubusercontent.com/platformio/platformio-core/develop/platformio/assets/system/99-platformio-udev.rules
fi

echo Run platformio from terminal
mkdir -p /usr/local/bin
ln -s ~/.platformio/penv/bin/platformio /usr/local/bin/platformio
ln -s ~/.platformio/penv/bin/pio /usr/local/bin/pio
ln -s ~/.platformio/penv/bin/piodebuggdb /usr/local/bin/piodebuggdb

# Unpack root at the end, so files are modified before
if [ -d /filesystem/root ]
then
  unpack /filesystem/root /
fi
