name: Build Image

on:
  #repository_dispatch:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v2
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS

    - name: Checkout Project Repository
      uses: actions/checkout@v2
      with:
        path: repository
        submodules: true

    - name: Download Raspbian Image
      run: |
        cd repository/src/image-raspios_lite_arm64
        wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_arm64_latest'

    - name: Update CustomPiOS Paths
      run: |
        cd repository/src
        ../../CustomPiOS/src/update-custompios-paths
    
    #- name: Build Image
    #  run: |
    #    sudo modprobe loop
    #    cd repository/src
    #    make build_arm64

    - name: version
      run: echo "::set-output name=version::$(grep DIST_VERSION repository/src/config | cut -d '=' -f 2)"
      id: version

    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ github.token }}

    #- name: Copy output
    #  id: copy
    #  env:
    #    NEXTCLOUD_USER: ${{ secrets.NEXTCLOUD_USER }}
    #    NEXTCLOUD_PASSWORD: ${{ secrets.NEXTCLOUD_PASSWORD }}
    #    NEXTCLOUD_URL: ${{ secrets.NEXTCLOUD_URL }}
    #  run: |
    #    source repository/src/config
    #    NOW=$(date +"%Y-%m-%d-%H%M")
    #    IMAGE=$NOW-devops-$DIST_VERSION

    #    cp repository/src/workspace-raspios_lite_arm64/*.img $IMAGE.img

    #    echo "::set-output name=image::$IMAGE"

    #    xz $IMAGE.img
    #    curl -u $NEXTCLOUD_USER:$NEXTCLOUD_PASSWORD -T $IMAGE.img.xz $NEXTCLOUD_URL       
