# This is a basic workflow to help you get started with Actions

name: CI ohne Artifakte

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "master" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v3
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS

    - name: Checkout Project Repository
      uses: actions/checkout@v3
      with:
        path: repository
        submodules: true

    - name: Download Raspbian Image
      run: |
        cd repository/src/image
        wget --continue --quiet  --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf_latest'
        cd ../image-raspios_lite_arm64
        wget --continue --quiet  --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_arm64_latest'
        cd ../image-ubuntu_arm64
        wget --continue --quiet --trust-server-names 'https://cdimage.ubuntu.com/releases/22.04/release/ubuntu-22.04.2-preinstalled-server-arm64+raspi.img.xz'

    - name: Update CustomPiOS Paths
      run: |
        cd repository/src
        ../../CustomPiOS/src/update-custompios-paths
    
    - name: Build Image
      run: |
        sudo modprobe loop
        cd repository/src
        make build_all

    - name: Version
      run: echo "version=$(grep DIST_VERSION repository/src/config | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
      id: version

    - name: Copy armhf output
      id: copy_armhf
      run: |
        source repository/src/config
        IMAGE=devops-${DIST_VERSION}_armhf

        cp repository/src/workspace-raspios/*.img ${IMAGE}.img
        xz ${IMAGE}.img
        echo "image=${IMAGE}.img.xz" >> $GITHUB_OUTPUT

    - name: Upload armhf Image
      uses: actions/upload-artifact@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        path: ${{ steps.copy_armhf.outputs.image }}
        name: ${{ steps.copy_armhf.outputs.image }}

    - name: Copy arm64 output
      id: copy
      run: |
        source repository/src/config
        IMAGE=devops-${DIST_VERSION}_arm64

        cp repository/src/workspace-raspios_lite_arm64/*.img ${IMAGE}.img
        xz ${IMAGE}.img
        echo "image=${IMAGE}.img.xz" >> $GITHUB_OUTPUT

    - name: Upload arm64 Image
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        path: ${{ steps.copy.outputs.image }}
        name: ${{ steps.copy.outputs.image }}

    #- name: Copy arm64 ubuntu output
    #  id: copy_ubuntu_arm64
    #  run: |
    #    source repository/src/config
    #    IMAGE=devops-${DIST_VERSION}_ubuntu_arm64

    #    cp repository/src/workspace-ubuntu_arm64/*.img ${IMAGE}.img
    #    xz ${IMAGE}.img
    #    echo "image=${IMAGE}.img.xz" >> $GITHUB_OUTPUT

    #- name: Upload arm64 ubuntu Image
    #  uses: actions/upload-release-asset@v1
    #  env:
    #    GITHUB_TOKEN: ${{ github.token }}
    #  with:
    #    upload_url: ${{ steps.create_release.outputs.upload_url }}
    #    asset_path: ${{ steps.copy_ubuntu_arm64.outputs.image }}
    #    asset_name: ${{ steps.copy_ubuntu_arm64.outputs.image }}
    #    asset_content_type: application/xz